### ISSUE TITLE
[BUG] Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by FestivusMiracle** [firstof9/ha-openei#67]
Home Assistant 2023.1.2 
Supervisor 2022.12.1 
Operating System 9.4 
Frontend 20230104.0 - latest 
--------
I have been unable to get this integration to work. I've followed the instructions, and tried two different API keys. I've tried several different electrical plans to see if maybe I was using a deprecated one as well. Can't figure what I'm doing wrong.

As per our conversation, here are the logs including traceback. Please feel free to reach out if I can help troubleshoot.

Logger: homeassistant
Source: custom_components/openei/init.py:127
Integration: OpenEI Utility Rates (documentation, issues)
First occurred: January 8, 2023 at 9:00:00 PM (1893 occurrences)
Last logged: 10:00:03 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/openei/init.py", line 120, in _async_refresh_data
    self._data = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/openei/init.py", line 159, in get_sensors
    value = getattr(rate, SENSOR_TYPES[sensor].key)
  File "/usr/local/lib/python3.10/site-packages/openeihttp/init.py", line 251, in all_rates
    adjs.append(rate[0]["adj"])
KeyError: 'adj'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/openei/init.py", line 127, in _async_refresh_data
    raise UpdateFailed() from exception
homeassistant.helpers.update_coordinator.UpdateFailed

**Comment by FestivusMiracle** [comment]
She rides!!! Integration is now working. Thanks for the quick work on this one.
